name: File Lister
on:
  push:
    branches:
      - master
    paths:
      - '**.tsv'
      - '**.csv'
jobs:
  tsvlister:
    name: TSV Lister
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy the Readmes
      run: |
        for i in `find ./src/ -type f -name "*.img";
        do
          echo "$i"
        done