name: File Lister
on:
  push:
    branches:
      - master
    paths:
      - '**.tsv'
      - '**.csv'
jobs:
  tsvlister:
    name: TSV Lister
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy the Readmes
      run: |
        for i in `find ./src/ -type f -name "*.tsv"`;
        do
          let sname = "$i"
          let sname = "${sname/.\/src\//.\/dist\/}"
          let sname = "${sname/.tsv/.txt}"
          echo "$sname"
        done